name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}


jobs:
  build-train-test-deploy:
    name: Train & Deploy Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Export DagsHub credentials
        run: |
          echo "DAGSHUB_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV
          echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
          
      - name: Login to Hugging Face
        run: |
          huggingface-cli login --token "$HF_TOKEN"

      - name: Train and Track Model (MLflow)
        run: |
          python main.py

      - name: Upload Tuned Models to HuggingFace Hub
        run: |
          python src/models_upload.py

      - name: Generate Docker Tag from Timestamp
        id: timestamp
        run: echo "tag=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: docker
        run: |
          TAG=${{ steps.timestamp.outputs.tag }}
          IMAGE_NAME=${{ env.DOCKERHUB_USERNAME }}/llm_nlp_app:$TAG
          echo "image_name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"

          echo "Building Docker Image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .

          echo "Pushing to DockerHub..."
          docker push $IMAGE_NAME
